### ISSUE TITLE
Configuration question

### ISSUE THREAD

**Issue by ScottHale** [reviewboard/rb-gateway#1]
Hello I am attempting to setup reviewboard gateway and I am a little confused by the configuration.
I am using git and have copies of the repositories on the reviewboard server.
I have installed and am running rb-gateway on the same server.

My repositories are hosted on AWS CodeCommit.

**rb-gateway config.json**
{
    "port": 8888, 
    "username": "AWSCodeCommitUserName",
    "password": "AWSCodeCommitUserPassword",
    "repositories": [
        {"name": "BuildConfiguration", "path": "/home/bitnami/BuildConfiguration/.git", "scm": "git"}
    ]
}

- Are the username and password in config.json supposed to be my credentials to access my git repository?

**In admin 'Add Repository'**

Name: BuildConfiguration
Hosting service: Review Board Gateway
Service URL: https://git-codecommit.us-west-2.amazonaws.com/v1/repos/BuildConfiguration
Account username: AWSCodeCommitUserName
Account password: AWSCodeCommitUserPassword
Repository type: Git
Repository Name: BuildConfiguration

- Is service URL supposed to point at  the rb-gateway(localhost:8888) or my git repository? 
Are the username and password in the _Repository Hosting_ section of _Add Repository_ supposed to be my git credentials?

- When I attempt to save the repository with the current configuration I get a red band across the screen and a 403 error with a message telling me to fix before I can save. If I go to the command line on the same server and clone with the same https credentials I have access. What am I missing?

Thanks in advance :)

**Comment by davidt** [comment]
OK, to answer your questions:

1. The username and password in config.json are whatever you want. These are what you'll put into the "Add repository" form as account username/password
2. The service URL should be the rb-gateway endpoint
3. Once you fix the service URL and username and password, it should work.

That said, if you have a local clone of your repository on the Review Board server(which is being fetched frequently via a cronjob), I'd suggest just avoiding rb-gateway entirely and configuring it as a git repo and point to the .git directory for the repository path.
