### ISSUE TITLE
Index out of range error on get branches

### ISSUE THREAD

**Issue by abosse55** [reviewboard/rb-gateway#2]
Hi, while using rb-gateway with Mercurial repositories, I found out that when you try do a "get branches" and the repository doesn't have any bookmarks, this line `Id:   fields[1],` (line 182) in repositories/hg.go method GetBranches(), causes an index out of range error.

Thanks

**Comment by davidt** [comment]
I didn't intend to have issues on for this repo. I've moved this over to our active bug tracker: https://hellosplat.com/s/beanbag/tickets/4792/
